[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node --experimental-global-webcrypto dist/index.js"
healthcheckPath = "/api/version"
healthcheckTimeout = 30

[deploy.envVariables]
PORT = "3001"
MEGA_EMAIL = "amrmansour8374@gmail.com"
MEGA_PASSWORD = "amrAMR000"
