services:
  - type: web
    name: lexpro-server
    env: node
    rootDirectory: packages/server
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/version
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        value: mongodb+srv://amr:amr@cluster0.nh9dfgl.mongodb.net/lexpro?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: lexpro-jwt-secret-2024
      - key: MEGA_EMAIL
        value: amrmansour8374@gmail.com
      - key: MEGA_PASSWORD
        value: amrAMR000
      - key: CLIENT_URL
        value: '*'
